spring:
  application:
    name: link-app
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:oracle:thin:@localhost:3333:ORCLCDB
    username: some
    password: some_pass
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
      type: TRACE